version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend/src:/app/frontend/src # Это позволяет вам видеть изменения в реальном времени



